# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a6c76e872fa573eea136f8e610c01875feec0c6d3d69ae0a7397eb2b2bbba00c6990b47b030e2f77b48a53567995a61620748db40babd7a5448dd17651bec82

test:
  secret_key_base: a592d4bb6594880d95774e44e7c9f45bd7c3fb0e64757690b1f3b6ddf804d9254398579bd6d14baa1548ecbc0da2b8e8ebba4b41e2c2a5deaa671d085d65d7a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
